{
 "title": "Ganesha",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ganesha:nfs_requests:rate1m", "legendFormat": "{{ version }} {{ operation}}" }
   ]
  },
  {
   "title": "Mean (50%) latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ganesha:nfs_latency_percentile:rate1m{percentile=\"50\"}",
     "legendFormat": "{{ version }} {{ operation}}"
    }
   ]
  },
  {
   "title": "Total throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ganesha:nfs_request_bytes:rate1m",
     "legendFormat": "{{ version }} {{ operation}}"
    }
   ]
  },
  {
   "title": "Latency percentiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "1% latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_latency_percentile:rate1m{percentile=\"1\"}",
       "legendFormat": "{{ version }} {{ operation}}"
      }
     ]
    },
    {
     "title": "90% latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_latency_percentile:rate1m{percentile=\"90\"}",
       "legendFormat": "{{ version }} {{ operation}}"
      }
     ]
    },
    {
     "title": "Mean (50%) latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_latency_percentile:rate1m{percentile=\"50\"}",
       "legendFormat": "{{ version }} {{ operation}}"
      }
     ]
    },
    {
     "title": "95% latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_latency_percentile:rate1m{percentile=\"95\"}",
       "legendFormat": "{{ version }} {{ operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Read and write latency distributions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    { "title": "NFS v3", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 19 }, "options": { "content": " " } },
    { "title": "NFS v4", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 19 }, "options": { "content": " " } },
    {
     "title": "NFS v3 Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_latency_percentile:rate1m{operation=\"read\", version=\"nfs3\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    },
    {
     "title": "NFS v4 Read Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_latency_percentile:rate1m{operation=\"read\", version=\"nfs4\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    },
    {
     "title": "NFS v3 Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_latency_percentile:rate1m{operation=\"write\", version=\"nfs3\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    },
    {
     "title": "NFS v4 Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:nfs_latency_percentile:rate1m{operation=\"write\", version=\"nfs4\"}",
       "legendFormat": "{{ percentile }}%"
      }
     ]
    }
   ]
  },
  {
   "title": "Read and write request sizing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    { "title": "NFS v3", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 20 }, "options": { "content": " " } },
    { "title": "NFS v4", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 20 }, "options": { "content": " " } },
    {
     "title": "NFS v3 read request size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "ganesha:nfs_request_size_bytes:rate1m{operation=\"read\", version=\"nfs3\"}",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "NFS v4 read request size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "ganesha:nfs_request_size_bytes:rate1m{operation=\"read\", version=\"nfs4\"}",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "NFS v3 write request size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "ganesha:nfs_request_size_bytes:rate1m{operation=\"write\", version=\"nfs3\"}",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "NFS v4 write request size heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "ganesha:nfs_request_size_bytes:rate1m{operation=\"write\", version=\"nfs4\"}",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Export Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total read throughput (bytes/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ganesha:total_export_request_bytes:rate1m{operation=\"read\"}",
       "legendFormat": "{{ export }}"
      }
     ]
    },
    {
     "title": "Total request rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ganesha:total_export_requests:rate1m",
       "legendFormat": "{{ version }} {{ export}}"
      }
     ]
    },
    {
     "title": "Total write throughput (bytes/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ganesha:total_export_request_bytes:rate1m{operation=\"write\"}",
       "legendFormat": "{{ export }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Export latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean (50%) read latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:export_latency_percentile:rate1m{percentile=\"50\", operation=\"read\"}",
       "legendFormat": "{{ export }}"
      }
     ]
    },
    {
     "title": "Mean (50%) latency (all operations)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:export_latency_percentile:rate1m{percentile=\"50\"}",
       "legendFormat": "{{ operation }} {{ export }}"
      }
     ]
    },
    {
     "title": "90% read latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:export_latency_percentile:rate1m{percentile=\"90\", operation=\"read\"}",
       "legendFormat": "{{ export }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read throughput per client (nfs3 + nfs4)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ganesha:total_client_request_bytes:rate1m{operation=\"read\"}",
       "legendFormat": "{{ client }}"
      }
     ]
    },
    {
     "title": "Total request rate per client",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ganesha:total_client_requests:rate1m",
       "legendFormat": "{{ version }} {{ client }}"
      }
     ]
    },
    {
     "title": "Write throughput per client (nfs3 + nfs4)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "ganesha:total_client_request_bytes:rate1m{operation=\"write\"}",
       "legendFormat": "{{ client }}"
      }
     ]
    },
    {
     "title": "Mean (50%) read latency per client",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:client_latency_percentile:rate1m{percentile=\"50\", operation=\"read\"}",
       "legendFormat": "{{ version }} {{ client }}"
      }
     ]
    },
    {
     "title": "Client connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ganesha:active_client_connections",
       "legendFormat": "{{ activity }}"
      }
     ]
    },
    {
     "title": "Mean (90%) read latency per client",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "ganesha:client_latency_percentile:rate1m{percentile=\"90\", operation=\"read\"}",
       "legendFormat": "{{ version }} {{ client }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPCs  and worker threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPCs in flight",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ganesha:rpcs_in_flight", "legendFormat": "rpcs" }
     ]
    },
    {
     "title": "Worker threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ganesha:worker_threads", "legendFormat": "{{ label }}" }
     ]
    },
    {
     "title": "RPCs received / processed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "ganesha:rpcs_received:rate1m", "legendFormat": "received" },
      { "expr": "ganesha:rpcs_processed:rate1m", "legendFormat": "processed" }
     ]
    }
   ]
  }
 ]
}